

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASM.EmployeeManagement.DataAccess.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EmployeeEntities : DbContext
{
		public EmployeeEntities()
			   : base("name=EmployeeEntities")
		{
			this.Configuration.ProxyCreationEnabled = false;
		}

		public EmployeeEntities(string nameOrConnectionString) : base(nameOrConnectionString)
		{
			this.Configuration.ProxyCreationEnabled = false;
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserDetail> UserDetails { get; set; }

}

}

